### ISSUE TITLE
UnhandledPromiseRejectionWarning caused by this module not catching validation errors

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-tcp#121]
```console
(node:19077) UnhandledPromiseRejectionWarning: Error: invalid ip
    at module.exports (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-utils/src/ip-port-to-multiaddr.js:8:11)
    at module.exports (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-tcp/src/socket-to-conn.js:55:39)
    at Server.net.createServer (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-tcp/src/listener.js:23:20)
    at Server.emit (events.js:198:13)
    at TCP.onconnection (net.js:1520:8)
```

This can cause applications to crash.

**Comment by jacobheun** [comment]
My assumption is that we're getting a DNS address causing the invalid ip error. We need to wrap the calls to the utils function. Ideally we'd just use `multiaddr.fromNodeAddress`, but that doesn't support non ip addresses at the moment.

**Comment by vasco-santos** [comment]
@jacobheun I am not sure if this is because of getting a DNS address, since this throws on parameter validation and not on ip validation.

The stack trace is:

- https://github.com/libp2p/js-libp2p-tcp/blob/master/src/socket-to-conn.js#L55
- https://github.com/libp2p/js-libp2p-utils/blob/master/src/ip-port-to-multiaddr.js#L8

So, this immediately failing on the parameter validation, which makes me think that `ip-port-to-multiaddr` is receiving undefined. Anyway, I will PR shortly a better error support for the util

**Comment by jacobheun** [comment]
I believe the issue is related to a client disconnecting before the listener converts the connection. From the nodejs docs for remoteAddress

> Value may be undefined if the socket is destroyed (for example, if the client disconnected).

This is likely what we're seeing. I am adding a general catch in the listener for converting the socket to a `MultiaddrConnection`. Dial errors are caught in libp2p, but there is nothing to handle listener errors, so it can't throw.
